#!/bin/sh

#reboot fast on KernelPanic
echo 16 > /proc/sys/kernel/panic

echo "starting telnetd"
/usr/sbin/telnetd &

echo "install readout driver"
insmod /usr/local/bin/rdp_fifo_driver.ko

echo "install memory driver"
insmod /usr/local/bin/memory.ko     

echo "start register server"
/usr/local/bin/register.sh & 

echo "start GTS Leaf NUMEXO2 server"
/usr/local/bin/gts.sh &

