#!/bin/sh

echo "fast reboot on KernelPanic"
echo 16 > /proc/sys/kernel/panic

echo "starting telnetd"
/usr/sbin/telnetd &

if [ -e /NO_RDP_FIFO ]
then
  echo "no readout driver"
else
  echo "install readout driver"
  insmod /usr/local/bin/rdp_fifo_driver.ko
fi

echo "install memory driver"
insmod /usr/local/bin/memory.ko     

echo "start register server"
/usr/local/bin/register.sh & 

echo "start GTS Leaf NUMEXO2 server"
/usr/local/bin/gts.sh &

